// Reference: https://creatorlink.com/template
export type Template = {
  id: string;
  name: string;
  categories: string[];
  image: string;
  isNew: boolean;
};

export const templates: Template[] = [
  {
    id: 'acinonyx',
    name: '분양',
    categories: ['construct'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_acinonyx_kor_renew.jpg',
    isNew: true,
  },
  {
    id: 'company04',
    name: '회사소개 02',
    categories: ['company'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company04_thumb_en.png?1',
    isNew: true,
  },
  {
    id: 'company05',
    name: '회사소개 03',
    categories: ['company'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company05_thumb_ko.png?1',
    isNew: true,
  },
  {
    id: 'portfolio22',
    name: '일러스트레이터 01',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio_22_ko_thumb.jpg?1',
    isNew: true,
  },
  {
    id: 'company06',
    name: '회사소개 04',
    categories: ['company'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company06_thumb_ko.png?1',
    isNew: true,
  },
  {
    id: 'portfolio23',
    name: '일러스트레이터 02',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio_23_ko_thumb.jpg',
    isNew: true,
  },
  {
    id: 'mysticetus',
    name: '회사소개 07',
    categories: ['company'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_mysticetus_kor.jpg',
    isNew: false,
  },
  {
    id: 'academy04',
    name: '미술학원',
    categories: ['edu'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_academy_04_ko_thumb.jpg',
    isNew: true,
  },
  {
    id: 'rourei',
    name: '브랜드디자이너',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio09_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'academy05',
    name: '가죽공방',
    categories: ['edu'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_academy_05_thumb_ko.jpg',
    isNew: true,
  },
  {
    id: 'cafe04',
    name: '김밥분식',
    categories: ['cafe', 'franchise'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_cafe_04_ko_thumb.jpg',
    isNew: true,
  },
  {
    id: 'cafe05',
    name: '퓨전해물',
    categories: ['cafe', 'franchise'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_cafe_05_thumb_ko.jpg',
    isNew: true,
  },
  {
    id: 'company03',
    name: '회사소개 01 / 샐러드',
    categories: ['company', 'franchise'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company03_thumb_ko.png?1',
    isNew: true,
  },
  {
    id: 'company07',
    name: '회사소개 05 / 의약품',
    categories: ['company', 'product'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company07_thumb_ko.png?1',
    isNew: true,
  },
  {
    id: 'culture01',
    name: '박물관 01',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_culture_01_thumb.jpg',
    isNew: true,
  },
  {
    id: 'culture08',
    name: '아트홀',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_culture_08_ko_thumb.jpg',
    isNew: true,
  },
  {
    id: 'franchise01',
    name: '차',
    categories: ['franchise'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_franchise01_ko.jpg',
    isNew: true,
  },
  {
    id: 'product02',
    name: '스포츠웨어 / 요가',
    categories: ['product', 'shopping', 'sports'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_product_02_ko_thumb.jpg',
    isNew: true,
  },
  {
    id: 'academy02',
    name: '제과제빵학원',
    categories: ['edu'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_academy_02_thumb.jpg',
    isNew: false,
  },
  {
    id: 'academy03',
    name: '영어학원',
    categories: ['edu'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_academy_03_thumb_ko.jpg',
    isNew: false,
  },
  {
    id: 'beauty01',
    name: '스킨케어 01',
    categories: ['beauty'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_beauty_01_thumb.jpg',
    isNew: false,
  },
  {
    id: 'beauty02',
    name: '헤어',
    categories: ['beauty', 'shopping'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_beauty_02_thumb.jpg',
    isNew: false,
  },
  {
    id: 'beauty03',
    name: '네일아트',
    categories: ['beauty'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_beauty_03_thumb.jpg',
    isNew: false,
  },
  {
    id: 'beluga',
    name: '그래픽디자이너 04',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_beluga_kor.jpg',
    isNew: false,
  },
  {
    id: 'civettina',
    name: '전시회 01',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/newtpl07/culthumnail_03.jpg',
    isNew: false,
  },
  {
    id: 'company02',
    name: '회사소개 06',
    categories: ['company'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_company_02_thumb.jpg',
    isNew: false,
  },
  {
    id: 'culture02',
    name: '박람회 01',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_culture_02_thumb.jpg',
    isNew: false,
  },
  {
    id: 'culture07',
    name: '박물관 02',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_culture_07_ko_thumb.jpg?1',
    isNew: false,
  },
  {
    id: 'diazi',
    name: '박람회 02',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/dize_thumnail.png',
    isNew: false,
  },
  {
    id: 'euryzona',
    name: '인테리어 01',
    categories: ['construct'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_house02_ko.jpg',
    isNew: false,
  },
  {
    id: 'fennec',
    name: '건축디자이너',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_fennec_kor.jpg',
    isNew: false,
  },
  {
    id: 'fulica',
    name: '졸업전시회 01',
    categories: ['expo'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_fulica_kor_renew.jpg',
    isNew: false,
  },
  {
    id: 'gambieri',
    name: '그래픽디자이너 05',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_gambieri_kor.jpg',
    isNew: false,
  },
  {
    id: 'gerpi',
    name: '포토그래퍼 05',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio15_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'graysoni',
    name: '그래픽디자이너 01',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio04_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'gryphus',
    name: '웨딩드레스',
    categories: ['beauty', 'shopping'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_beauty05_ko.jpg',
    isNew: false,
  },
  {
    id: 'guanicoe',
    name: '스킨케어 02 / 화장품',
    categories: ['beauty', 'product', 'shopping'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_beauty_04_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'house05',
    name: '건설',
    categories: ['construct'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_house_05_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'iliensis',
    name: '카페 02',
    categories: ['cafe'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_cafe02_thumb_ko.png?1',
    isNew: false,
  },
  {
    id: 'inscinius',
    name: '제품디자이너',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio21_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'itatsi',
    name: '포토그래퍼 04',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio13_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'javan',
    name: '서핑',
    categories: ['sports'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_sports01_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'jefferyi',
    name: '포토그래퍼 08',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_jefferyi_kor.jpg',
    isNew: false,
  },
  {
    id: 'kidogo',
    name: '그래픽디자이너 02',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio07_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'leopardus',
    name: '전시회 02',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/newtpl07/culthumnail_06.jpg',
    isNew: false,
  },
  {
    id: 'lilliae',
    name: '포토그래퍼 03',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_lilliae_kor.jpg',
    isNew: false,
  },
  {
    id: 'luscinius',
    name: '그래픽디자이너 03',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_luscinius_kor.jpg',
    isNew: false,
  },
  {
    id: 'lutreola',
    name: '식물',
    categories: ['product'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_lutreola_kor.jpg',
    isNew: false,
  },
  {
    id: 'nigripes',
    name: '카페 01 / 커피',
    categories: ['cafe', 'shopping'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_img_nigripes_ko.jpg',
    isNew: false,
  },
  {
    id: 'ochotona',
    name: '포토그래퍼 02',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio03_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'otocyon',
    name: '졸업전시회 05',
    categories: ['expo'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_otocyon_kor.jpg',
    isNew: false,
  },
  {
    id: 'pagensis',
    name: '로고디자이너',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio11_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'pardinus',
    name: '인테리어 03 / 졸업전시회 02',
    categories: ['construct', 'expo'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_pardinus_kor_renew.jpg?1',
    isNew: false,
  },
  {
    id: 'pennantii',
    name: '플로리스트',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio19_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'phocoena',
    name: '졸업전시회 04',
    categories: ['expo'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_phocoena_kor.jpg',
    isNew: false,
  },
  {
    id: 'portfolio06',
    name: '산업디자이너',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio_06_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'portfolio16',
    name: '포토그래퍼 06',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_portfolio_16_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'pteromys',
    name: '주얼리',
    categories: ['product', 'shopping'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_img_pteromys.jpg',
    isNew: false,
  },
  {
    id: 'rubicola',
    name: '도자기 / 도예공방',
    categories: ['product', 'shopping', 'edu'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_rubicola_kor.jpg',
    isNew: false,
  },
  {
    id: 'saola',
    name: '디자인에이전시',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_img_saola.jpg',
    isNew: false,
  },
  {
    id: 'simensis',
    name: '발레공연',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_simensis_kor.jpg',
    isNew: false,
  },
  {
    id: 'sports03',
    name: '리조트',
    categories: ['sports'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_sports_03_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'sports04',
    name: '요트',
    categories: ['sports'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_sports_04_ko_thumb.jpg',
    isNew: false,
  },
  {
    id: 'tayra',
    name: '스킨케어 03',
    categories: ['beauty'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_shop06_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'tremarctos',
    name: '졸업전시회 03',
    categories: ['expo'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_tremarctos_kor.jpg',
    isNew: false,
  },
  {
    id: 'viverra',
    name: '포토그래퍼 01',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_viverra_kor_renew.jpg',
    isNew: false,
  },
  {
    id: 'waldeni',
    name: '포토그래퍼 07',
    categories: ['studio'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_waldeni_kor.jpg',
    isNew: false,
  },
  {
    id: 'walie',
    name: '콘서트',
    categories: ['culture'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/temp_culture09_thumb_ko.png',
    isNew: false,
  },
  {
    id: 'wintoni',
    name: '인테리어 02',
    categories: ['construct'],
    image: 'https://storage.googleapis.com/i.addblock.net/sample/tpl_wintoni_kor.jpg',
    isNew: false,
  },
];
